### ISSUE TITLE
Spine version

### ISSUE THREAD

**Issue by VincentSai** [Reinisch/Darkest-Dungeon-Unity#10]
Hi, may I know which version of Spine you using?
I try to use Spine 2.5, but it will get a lots error.

Assets/Scripts/Managers/RaidSceneManager.cs(7287,96): error CS1061: Type `Spine.TrackEntry' does not contain a definition for `EndTime' and no extension method `EndTime' of type `Spine.TrackEntry' could be found. Are you missing an assembly reference?
Assets/Scripts/Raid/Events/RaidEvents.cs(163,27): error CS1061: Type `Spine.Unity.SkeletonAnimation' does not contain a definition for `Reset' and no extension method `Reset' of type `Spine.Unity.SkeletonAnimation' could be found. Are you missing an assembly reference?
Assets/Scripts/Raid/Party/AnimatedEffect.cs(53,18): error CS1061: Type `Spine.Unity.BoneFollower' does not contain a definition for `DoUpdate' and no extension method `DoUpdate' of type `Spine.Unity.BoneFollower' could be found. Are you missing an assembly reference?

**Comment by Reinisch** [comment]
I'm not sure, probably I also made some modifications.
I can upload all ignored plugins and .cs files if you want.

But I can't upload any graphics, maybe if you really want to fork and change something I can send ignored files on mail.

**Comment by arusdef** [comment]
@Reinisch That would be incredible. I wrote you already.
