### ISSUE TITLE
Confusion in v1.0.3-PvP-Only's release notes.

### ISSUE THREAD

**Issue by atp-tha** [Reinisch/Darkest-Dungeon-Unity#11]
The version said it's PvP only but when I look in release notes Non PvP features are listed.

Does this 'v1.0.3-PvP-Only' include all features both PvP and Non PvP ?

**Comment by Reinisch** [comment]
Unfortunately I disabled campaign in final build since DD devs didn't like that it was almost full copy of the original.

Last version actually has everything, the only difference is "Campaign" button disabled.
