### ISSUE TITLE
Anyway to import into unity?

### ISSUE THREAD

**Issue by holycow88** [Reinisch/Darkest-Dungeon-Unity#15]
Hi I am new to coding and wanted to know how I would be able to view the classes and files within Unity, thanks and great work :)

**Comment by Reinisch** [comment]
Just clone this repository or download zip then open project in Unity on Darkest-Dungeon-Unity folder, it should work, but game assets are not uploaded, only scripts and binaries.

**Comment by gopokyo-colinn** [comment]
Where do we put game assets?  what is the folder structure?
