### ISSUE TITLE
Darkest Dungeon in Unity Editor

### ISSUE THREAD

**Issue by Syntherz** [Reinisch/Darkest-Dungeon-Unity#16]
Hello! I'm a student from a Portuguese university called UTAD and i'm currently working with unity only for academic purposes. The project that i'm working on is basically a Darkest Dungeon version in unity, though i'm limited in terms of assets, i can't find any that are free and fitting to the style.
Is there a way to get the original assets or others that are somehow similar?

Thanks in advance.

**Comment by Reinisch** [comment]
I don't know about other similar assets but if you want original Darkest Dungeon assets in Unity then just download Spine Runtime for Unity and it will import any DD assets automatically, you only need to change some file extensions. If it doesn't work I can send you download link on mail with imported assets for this project.

**Comment by Syntherz** [comment]
I worked around that a bit but i think it's better if you could send me the download link as you said before. If possible of course.
Thanks once again for the help!
