### ISSUE TITLE
Can't start the game in Unity Editor

### ISSUE THREAD

**Issue by jeansusgodney** [Reinisch/Darkest-Dungeon-Unity#18]
The Campaign Menu seems to miss some icons like Enter Town / Start The Game

And I also always get this error Message
NullReferenceException: Object reference not set to an instance of an object
QuirkInfo..ctor (System.String quirkName) (at Assets/Scripts/Character/QuirkInfo.cs:20)
SaveHeroData..ctor (Int32 id, System.String name, System.String heroClass, Int32 resolveLevel, Int32 resolveXp, Int32 stressLevel, Int32 weaponLevel, Int32 armorLevel, System.String leftTrinket, System.String rightTrinket, System.String[] quirks) (at Assets/Scripts/Setup/SaveSystem/SaveHeroData.cs:54)
SaveCampaignData.PopulateStartingEstateData () (at Assets/Scripts/Setup/SaveSystem/SaveCampaignData.cs:168)
SaveLoadManager.WriteStartingSave (.SaveCampaignData saveData) (at Assets/Scripts/Setup/SaveSystem/SaveLoadManager.cs:379)
SaveSlot.SaveNamingCompleted () (at Assets/Scripts/Setup/SaveSystem/SaveSlot.cs:93)
UnityEngine.Events.InvokableCall.Invoke (System.Object[] args) (at /Users/builduser/buildslave/unity/build/Runtime/Export/UnityEvent.cs:159)
UnityEngine.Events.UnityEvent`1[T0].Invoke (.T0 arg0) (at /Users/builduser/buildslave/unity/build/Runtime/Export/UnityEvent_1.cs:65)
UnityEngine.UI.InputField.SendOnSubmit () (at /Users/builduser/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/InputField.cs:1582)
UnityEngine.UI.InputField.DeactivateInputField () (at /Users/builduser/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/InputField.cs:2306)
UnityEngine.UI.InputField.OnDeselect (UnityEngine.EventSystems.BaseEventData eventData) (at /Users/builduser/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/InputField.cs:2316)
UnityEngine.EventSystems.ExecuteEvents.Execute (IDeselectHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at /Users/builduser/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:113)
UnityEngine.EventSystems.ExecuteEvents.Execute[IDeselectHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor) (at /Users/builduser/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update()

I can send you a screenshot of my valid purchase of the game. I just wanna know how the game was built. Thanks

**Comment by Reinisch** [comment]
It looks like some quirk is missing from database, but other people never experienced this, are you sure that nothing is edited and you never opened project without any assets? For everything to work properly you need:

1. Install Unity 2017.3.0f3
2. Fork or download zip for this repo
3. Download assets https://drive.google.com/drive/folders/0B4fCt9AnmePGNDJGcmFZckpTanM
4. Extract everything from there and only open unity project after this

Also check that JsonQuirks.json has no changes in diff.

**Comment by jeansusgodney** [comment]
Hi thanks for answering.

I was trying it on my MacBook, it didn't work.

I tried it on my Windows PC and it worked. 

Wierd heh?
