### ISSUE TITLE
Unfortunately, it is currently not possible to build

### ISSUE THREAD

**Issue by pavlo-kravchenko** [Reinisch/Darkest-Dungeon-Unity#21]
Using actual Unity even after updating all the necessary frameworks does not work beyond the second scene

**Comment by RED3480** [comment]
> Using actual Unity even after updating all the necessary frameworks does not work beyond the second scene

If you utilize the resources from the other issue thread. https://drive.google.com/drive/folders/0B4fCt9AnmePGNDJGcmFZckpTanM?resourcekey=0-i1228-uq1SJcdtxXZOg-eg&usp=sharing
it works rather nicely

**Comment by Crawfish-h** [comment]
@RED3480 How exactly did you get this project to work because when I try, I get a bunch of nullreferenceexception errors and an error saying "FMOD studio project path not set."

**Comment by kewtie314** [comment]
> > Using actual Unity even after updating all the necessary frameworks does not work beyond the second scene
> 
> If you utilize the resources from the other issue thread. https://drive.google.com/drive/folders/0B4fCt9AnmePGNDJGcmFZckpTanM?resourcekey=0-i1228-uq1SJcdtxXZOg-eg&usp=sharing it works rather nicely

How did you actually get it running in Unity? I've followed what's been said in [this issue](https://github.com/Reinisch/Darkest-Dungeon-Unity/issues/18#issuecomment-480788332). 
Installed Unity 2017.03.0f3
Downloaded a zip of the Unity project repo
Stuck the asset files you've shared into the project folder's Asset folder
And then opened the project
Yet I get a ton of "Screen position out of view" and "Sprites can not be generated from textures with NPOT scaling."
  
`Screen position out of view frustum (screen pos 0.000000, 0.000000, 1000.000000) (Camera rect 0 0 0 0)
UnityEngine.Camera:Render()
SkeletonDataAssetInspector:DoRenderPreview(Boolean) (at Assets/Spine/SpineUnity/Editor/SkeletonDataAssetInspector.cs:687)
SkeletonDataAssetInspector:RenderStaticPreview(String, Object[], Int32, Int32) (at Assets/Spine/SpineUnity/Editor/SkeletonDataAssetInspector.cs:941)
UnityEditor.AssetPreviewUpdater:CreatePreviewForAsset(Object, Object[], String)
`

`NullReferenceException: Object reference not set to an instance of an object
SpineEditorUtilities.IngestSpineAtlas (UnityEngine.TextAsset atlasText) (at Assets/Spine/SpineUnity/Editor/SpineEditorUtilities.cs:730)
SpineEditorUtilities.ImportSpineContent (System.String[] imported, Boolean reimport) (at Assets/Spine/SpineUnity/Editor/SpineEditorUtilities.cs:298)
SpineEditorUtilities.OnPostprocessAllAssets (System.String[] imported, System.String[] deleted, System.String[] moved, System.String[] movedFromAssetPaths) (at Assets/Spine/SpineUnity/Editor/SpineEditorUtilities.cs:257)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.AssetPostprocessingInternal.PostprocessAllAssets (System.String[] importedAssets, System.String[] addedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromPathAssets) (at C:/buildslave/unity/build/Editor/Mono/AssetPostprocessor.cs:27)`
